### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by Codename-Ps** [ThisTestUser/FarLandsModV2#13]
Does this add farther,fartherer,farthest lands?

**Comment by ThisTestUser** [comment]
It does, but I'm skeptical that the fartherer/farthest lands exist, as the "jump" in the terrain doesn't occur in vanilla (more info here: https://github.com/ThisTestUser/FarLandsChronicles/blob/master/Chapter%205%20-%20The%20Great%20Beyond%20(1.12.2)/Part%201%20-%20Fartherer-est%20Lands%20(no%20fix).md).
