### ISSUE TITLE
No longer works on 1.17.1

### ISSUE THREAD

**Issue by TwelvianZeta** [ThisTestUser/FarLandsModV2#14]
Maybe a v3 is needed but this no longer works in forge 1.17.1 and might also be broken on forge 1.16.5 36.1.66+

**Comment by ThisTestUser** [comment]
The mod still works on the latest version of Forge 1.16.5, but not 1.17.1. I'm trying to see why this is, but I don't think v3 is needed for now.

**Comment by TwelvianZeta** [comment]
mod build crashes if you teleport too far

**Comment by ThisTestUser** [comment]
That's an issue with aquifiers in the Caves and Cliffs datapack. I'll probably fix it next release.

**Comment by ThisTestUser** [comment]
Everything that is gamebreaking should be fixed now.
