### ISSUE TITLE
1.18 Crashes upon teleporting to edge

### ISSUE THREAD

**Issue by SleepyBoi2852** [ThisTestUser/FarLandsModV2#16]
So when i try to teleport to the farlands (The Command was /tp @s 2147483646 ~ ~ ~), This Crashes.
Error Log:

> [Render thread/INFO]: [CHAT] An unexpected error occurred trying to execute that command

> Negative index in crash report handler (0/10)
> [10:37:30] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Ticking player
> 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:145) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2354!:?]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ArrayIndexOutOfBoundsException
> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 8/12/21, 10:37 am
> Description: Ticking player
> 
> java.lang.ArrayIndexOutOfBoundsException: null
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:500) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
> -- Player being ticked --
> Details:
> 	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
> 	Entity ID: 228
> 	Entity Name: AAAAAAAAAAAAA
> 	Entity's Exact location: 2147483646.50, 89.99, -175.31
> 	Entity's Block location: World: (2147483646,89,-176), Section: (at 14,9,0 in 134217727,5,-11; chunk contains blocks 2147483632,-64,-176 to 2147483647,319,-161), Region: (4194303,-1; contains chunks 134217696,-32 to 134217727,-1, blocks 2147483136,-64,-512 to 2147483647,319,-1)
> 	Entity's Momentum: 0.00, 0.00, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: null
> Stacktrace:
> 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:500) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:205) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,xf:fml:farlandsmod:ServerPlayNetHandler}
> 	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading}
> 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading}
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,xf:fml:farlandsmod:Server}
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,xf:fml:farlandsmod:Server}
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,xf:OptiFine:default}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,xf:fml:farlandsmod:Server}
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,xf:fml:farlandsmod:Server}
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.18
> 	Minecraft Version ID: 1.18
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.1, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
> 	Memory: 2251016192 bytes (2146 MiB) / 3590324224 bytes (3424 MiB) up to 4294967296 bytes (4096 MiB)
> 	CPUs: 4
> 	Processor Vendor: GenuineIntel
> 	Processor Name: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
> 	Identifier: Intel64 Family 6 Model 60 Stepping 3
> 	Microarchitecture: Haswell (Client)
> 	Frequency (GHz): 3.19
> 	Number of physical packages: 1
> 	Number of physical CPUs: 4
> 	Number of logical CPUs: 4
> 	Graphics card #0 name: AMD FirePro W7000
> 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x6808
> 	Graphics card #0 versionInfo: DriverVersion=27.20.14534.2
> 	Graphics card #1 name: Intel(R) HD Graphics 4600
> 	Graphics card #1 vendor: Intel Corporation (0x8086)
> 	Graphics card #1 VRAM (MB): 1024.00
> 	Graphics card #1 deviceId: 0x0412
> 	Graphics card #1 versionInfo: DriverVersion=20.19.15.4624
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 1.60
> 	Memory slot #0 type: DDR3
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 1.60
> 	Memory slot #1 type: DDR3
> 	Virtual memory max (MB): 20357.04
> 	Virtual memory used (MB): 17166.71
> 	Swap memory total (MB): 4087.52
> 	Swap memory used (MB): 147.32
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
> 	Server Running: true
> 	Player Count: 1 / 8; [ServerPlayer['AAAAAAAAAAAAA'/228, l='ServerLevel[fardland]', x=2147483646.50, y=89.99, z=-175.31]]
> 	Data Packs: vanilla, mod:farlandsmod (incompatible), mod:forge
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
> 	OptiFine Version: OptiFine_1.18_HD_U_H3
> 	OptiFine Build: 20211206-183717
> 	Render Distance Chunks: 5
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 3.2.14758 Core Profile Forward-Compatible Context FireGL 21.Q1 27.20.14534.2
> 	OpenGlRenderer: AMD FirePro W7000
> 	OpenGlVendor: ATI Technologies Inc.
> 	CpuCount: 4
> 	ModLauncher: 9.0.7+91+master.8569cdf
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		 mixin PLUGINSERVICE 
> 		 eventbus PLUGINSERVICE 
> 		 object_holder_definalize PLUGINSERVICE 
> 		 runtime_enum_extender PLUGINSERVICE 
> 		 capability_token_subclass PLUGINSERVICE 
> 		 accesstransformer PLUGINSERVICE 
> 		 runtimedistcleaner PLUGINSERVICE 
> 		 mixin TRANSFORMATIONSERVICE 
> 		 OptiFine TRANSFORMATIONSERVICE 
> 		 fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		javafml@null
> 	Mod List: 
> 		client-1.18-20211130.085255-srg.jar               |Minecraft                     |minecraft                     |1.18                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		farlandsv2-1.1.1.jar                              |Far Lands Mod                 |farlandsmod                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
> 		forge-1.18-38.0.16-universal.jar                  |Forge                         |forge                         |38.0.16             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 	Crash Report UUID: af6e9f33-8bd3-43d0-ab9a-1644a2386892
> 	FML: 38.0
> 	Forge: net.minecraftforge:38.0.16
> #@!@# Game crashed! Crash report saved to: #@!@# H:\MultiMC\instances\farfland\.minecraft\crash-reports\crash-2021-12-08_10.37.30-server.txt
> AL lib: (EE) alc_cleanup: 1 device not closed
> Process exited with code -1.

**Comment by ThisTestUser** [comment]
Teleporting close to the integer limit (2^31-1) is not supported. Also 1.18 support has not come out yet.
