### ISSUE TITLE
Remove 20 million vertical teleportation limit

### ISSUE THREAD

**Issue by muzikbike** [ThisTestUser/FarLandsModV2#5]
This mod removes the horizontal tp limits, why not the vertical limits?

![2020-07-12_17 12 39](https://user-images.githubusercontent.com/52297970/87251364-0c932e00-c463-11ea-875a-6c4c55c84448.png)
![2020-07-12_17 12 34](https://user-images.githubusercontent.com/52297970/87251365-0d2bc480-c463-11ea-9855-bad197279eb7.png)

**Comment by ThisTestUser** [comment]
You should be able to teleport up the integer limit now, but the game will crash if you try to go further (this also happens for the X and Z axis).
